version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RIPPER_ARGS: "-s IP -p PORT -q 10000"
    deploy:
      replicas: 4
      restart_policy:
        condition: any